apiVersion: v1
kind: Service
metadata:
  name: creditbazaar
  namespace: default
  labels:
    app: creditbazaar
spec:
  selector:
    app: creditbazaar
  type: LoadBalancer
  ports:
    - name: http
      port: 8080
